CREATE TABLE order_details (
  ID SERIAL PRIMARY KEY,
  STATUS ORDER_STATUS_TYPE,
  LAST_UPDATE_ON TIMESTAMP WITH TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
  LAST_LOCATION VARCHAR(2047),
  PLACED_BY_USER_ID INTEGER NOT NULL,
  CARRIER_ID INTEGER NOT NULL,
  CONSTRAINT order_user_fk_1 FOREIGN KEY (PLACED_BY_USER_ID) REFERENCES user_details (id),
  CONSTRAINT order_carrier_user_fk_1 FOREIGN KEY (CARRIER_ID) REFERENCES user_details (id)
);