CREATE TABLE order_details (
  ID SERIAL PRIMARY KEY,
  STATUS ORDER_STATUS_TYPE,
  LAST_UPDATE_ON TIMESTAMP WITH TIME ZONE DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
  LAST_LOCATION VARCHAR(2047),
  BELONGS_TO_USER_ID INTEGER,
  CONSTRAINT order_user_fk_1 FOREIGN KEY (BELONGS_TO_USER_ID) REFERENCES user_details (id)
);