CREATE TABLE user_profile (
  ID SERIAL PRIMARY KEY,
  DOB DATE NOT NULL,
  ADDRESS VARCHAR(1023) NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  COUNTRY VARCHAR(255) NOT NULL,
  GOVERNMENT_PHOTO_ID BYTEA NOT NULL,
  PINCODE VARCHAR(10) NOT NULL,
  OCCUPATION VARCHAR(255) NOT NULL,
  FREQUENT_FLYER BOOLEAN NOT NULL,
  PHOTO BYTEA NOT NULL,
  PHONE_NUMBER VARCHAR(13) NOT NULL
);