CREATE TABLE delivery_details (
  ID SERIAL PRIMARY KEY,
  BOARDING_LOCATION VARCHAR(511) NOT NULL,
  TRAVELLING_DATE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
  ITINERARY_PHOTO BYTEA NOT NULL,
  MAX_WEIGHT FLOAT NOT NULL,
  REMARKS VARCHAR(2047)

  DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);