CREATE TABLE courier_details (
  ID SERIAL PRIMARY KEY,
  LENGTH INT NOT NULL,
  WIDTH INT NOT NULL,
  HEIGHT INT NOT NULL,
  WEIGHT FLOAT NOT NULL,
  CONTENT VARCHAR(500) NOT NULL,
  IS_INFLAMABLE BOOLEAN NOT NULL DEFAULT FALSE,
  IS_BREAKABLE BOOLEAN NOT NULL DEFAULT FALSE,
  IS_TOBACCO BOOLEAN NOT NULL DEFAULT FALSE,
  ESTIMATED_PRICE FLOAT NOT NULL,
  IS_INSURANCE BOOLEAN NOT NULL DEFAULT FALSE,
  BILL_PHOTO BYTEA NOT NULL

);